on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '* * * * *'

name: Case Data Updates

jobs:
  render:
    name: Case Data Updates
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install dependencies
        run: Rscript -e 'install.packages(c("tidyverse","jsonlite"))'
      - name: Scrape the data
        run: Rscript Case_data_updates.R
      - name: Commit results
        run: |
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
